version: '3'
services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: always
    ports:
     - "27017:27017"
    volumes:
     - /data/mongodb/db:/data/db # 挂载数据目录
     - /data/mongodb/log:/var/log/mongodb  # 挂载日志目录
     - /data/mongodb/config:/etc/mongo  # 挂载配置目录
    # command: --config /docker/mongodb/mongod.conf # 配置文件