version: '3'
services:
  jenkins:
    image: 'jenkins/jenkins:2.349'
    container_name: jenkins
    restart: always
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - '/data/jenkins_home:/var/jenkins_home'
