# redis yml文件内容
version: '3'

services:
  redis:
    image: redislabs/rejson:latest
    container_name: redisjson
    restart: always
    ports:
      - 6379:6379
    networks:
      - redisnetwork
    volumes:
      - /data/docker/data/redis/data:/data
      - /data/docker/data/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /data/docker/data/redis/logs:/logs
    command: /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf"
networks:
  redisnetwork:
  external: true
