# redis yml文件内容
version: '3'

services:
  redis:
    image: redis:6.0
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - redisnetwork
    volumes:
      - /e/docker/redis/data:/data
      - /e/docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /e/docker/redis/logs:/logs
    command: /bin/bash -c "redis-server /e/docker/redis/redis.conf"
networks:
  redisnetwork: #    external: true
